critical:
    - '(Critical|critical|Urgent|urgent)'
documentation:
    - '(Doc|doc|Documentation|documentation)'
configuration_files:
    - '(Config|config|Configuration|configuration)'
gdrive:
    - '(Gdrive|Drive|gdrive|drive|)'
enhancement:
    - '(Improve|improve|Improvement|improvement|Enhance|enhance|Enhancement|enhancement)'
