# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
    - '(critical|urgent)'
documentation:
    - '(gdrive|drive)'
enhancement:
    - '(improve|improvement|enhance|enhancement)'
