libraries:
  "Movies operations":
    library_name: "Movies"
    schedule: daily
    operations:
      assets_for_all: true

  "TV Shows operations":
    library_name: "TV Shows"
    schedule: daily
    operations:
      assets_for_all: true

  "Kid Movies operations":
    library_name: "Kid Movies"
    schedule: daily
    operations:
      assets_for_all: true

  "Anime Shows operations":
    library_name: "Anime Shows"
    schedule: daily
    operations:
      assets_for_all: true

  "Anime Movies operations":
    library_name: "Anime Movies"
    schedule: daily
    operations:
      assets_for_all: true

settings:
  cache: true
  cache_expiration: 60
  show_missing_assets: true
  asset_directory: /assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: false
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
  run_order:
  - operations
  - metadata
  - collections
  - overlays

webhooks:
  error: notifiarr
  version: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  changes: notifiarr
  delete: notifiarr

plex:
  url:
  token:
  timeout: 60
  db_cache: 10240
  clean_bundles: false
  empty_trash: false
  optimize: false

tmdb:
  apikey:
  language: en
  cache_expiration: 60
  region:

notifiarr:
  apikey:

trakt:
  client_id:
  client_secret:
  authorization:
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:
  pin:
